name: Check for vulnerabilities 

on: 
  push:
    branches:
      - main
  
  pull_request:


jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
     
    - name: open src folder and install node modules
      run: cd src && npm install
    - name: open src folder and check for vulnerabilities
      run: cd src && npm audit
     

      
