name: Check for vulnerabilities 

on: 
  push:
    branches:
      - release
  
  pull_request:
    branches:
      - release


jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-14-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-14-
     
    - name: open src folder and install node modules
      run: cd src && npm install
    - name: open src folder and check for vulnerabilities
      run: cd src && npm audit --production
