name: Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lintcode:
    name: Backend JS lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - run: cd backend && npm ci --legacy-peer-deps --force
      - run: cd backend && npm run lint:code

  tests:
    name: Backend Meteor Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Checkout leaonline:corelib repo
        uses: actions/checkout@v4
        with:
          repository: leaonline/corelib
          path: github/corelib


      - name: Checkout leaonline:service-registry repo
        uses: actions/checkout@v4
        with:
          repository: leaonline/service-registry
          path: github/service-registry

      # CACHING
      - name: Install Meteor
        id: cache-meteor-install
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: v3-meteor-${{ hashFiles('.meteor/versions') }}
          restore-keys: |
            v3-meteor-

      - name: Cache Meteor build
        id: cache-meteor-build
        uses: actions/cache@v4
        with:
          path: |
            .meteor/local/resolver-result-cache.json
            .meteor/local/plugin-cache
            .meteor/local/isopacks
            .meteor/local/bundler-cache/scanner
          key: v3-meteor_build_cache-${{ github.ref }}-${{ github.sha }}
          restore-key: |
            v3-meteor_build_cache-

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: '3.0.2'

      - name: Install NPM Dependencies
        run: cd backend && meteor npm ci --legacy-peer-deps --force

      - name: Run Tests
        run: cd backend && sh ./test.sh -c -o

# TODO add coverage checks etc.
#      - name: Upload coverage
#        uses: actions/upload-artifact@v2
#        with:
#          name: coverage-folder
#          path: backend/.coverage/
#
#  coverage:
#    name: Coverage report
#    runs-on: ubuntu-latest
#    needs: [tests]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Download coverage
#        uses: actions/download-artifact@v2
#        with:
#          name: coverage-folder
#          path: backend/.coverage/
#
#
#      - name: Coverage Report
#        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
#        with:
#          path: ".coverage/lcov.info"
#          min_coverage: 95 # TODO increase to 95!

  docs:
    name: Backend Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - run: cd backend && npm ci --legacy-peer-deps --force
      - run: cd backend && npm run build:docs
