name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      releasetag:
        required: true
        description: 'Release tag'
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: fetch Semikolon font file
      env: FONT_URL: ${{ secrets.FONT_URL }}
      run: |
        FILE_NAME=$(basename FONT_URL)
        wget -q FONT_URL -O src/assets/fonts/${FILE_NAME}

    - name: install node modules
      run: cd src && npm ci && npm install --global expo-cli
      
    - name: eject from expo project
      run: cd src && npx expo eject --non-interactive
      
    - name: build apk
      run: cd src/android && ./gradlew assembleRelease
    
    - name: upload apk file
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: src/android/app/build/outputs/apk/release/
