name: JSDOC Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    
    - name: install node modules
      run: cd src && npm ci
    - name: run jsdoc
      run: cd src && npm run docs
