name: lint test

on:
  push:
    branches:
      - main
      - master
      - move-to-react-native
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: install node modules
      run: npm install
    - name: run standard js
      run: npx standard --env jest --env mocha
      
