name: Test

on:
  push:
    branches:
      - main
      - master
      - move-to-react-native
      
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        
        - name: open src folder
          uses: cd src
          
        - name: checkout
          uses: actions/checkout@v2
        
        - name: setup node
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        
        - name: install node modules
          run: npm init -y && npm install
        
        - name: intall jest 
          run: npm install --save-dev jest 
        
        - name: run jest tests
          run: jest